import { Montserrat } from "next/font/google";
import "./globals.css";

import Header from "@/components/Layout/Header/Header";
import Footer from "@/components/Layout/Footer/Footer";




const montserrat = Montserrat({
  variable: "--montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Химчистка",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${montserrat.variable}`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
